#!/usr/bin/env python
# coding: utf-8

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from yacs.config import CfgNode as CN


# pose_multi_resoluton_net related params
HIGHER_RESOLUTION_NET = CN()
HIGHER_RESOLUTION_NET.PRETRAINED_LAYERS = ['*']
HIGHER_RESOLUTION_NET.STEM_INPLANES = 64
HIGHER_RESOLUTION_NET.FINAL_CONV_KERNEL = 1

HIGHER_RESOLUTION_NET.STAGE1 = CN()
HIGHER_RESOLUTION_NET.STAGE1.NUM_MODULES = 1
HIGHER_RESOLUTION_NET.STAGE1.NUM_BRANCHES = 1
HIGHER_RESOLUTION_NET.STAGE1.NUM_BLOCKS = [4]
HIGHER_RESOLUTION_NET.STAGE1.NUM_CHANNELS = [64]
HIGHER_RESOLUTION_NET.STAGE1.BLOCK = 'BOTTLENECK'
HIGHER_RESOLUTION_NET.STAGE1.FUSE_METHOD = 'SUM'

HIGHER_RESOLUTION_NET.STAGE2 = CN()
HIGHER_RESOLUTION_NET.STAGE2.NUM_MODULES = 1
HIGHER_RESOLUTION_NET.STAGE2.NUM_BRANCHES = 2
HIGHER_RESOLUTION_NET.STAGE2.NUM_BLOCKS = [4, 4]
HIGHER_RESOLUTION_NET.STAGE2.NUM_CHANNELS = [24, 48]
HIGHER_RESOLUTION_NET.STAGE2.BLOCK = 'BOTTLENECK'
HIGHER_RESOLUTION_NET.STAGE2.FUSE_METHOD = 'SUM'

HIGHER_RESOLUTION_NET.STAGE3 = CN()
HIGHER_RESOLUTION_NET.STAGE3.NUM_MODULES = 1
HIGHER_RESOLUTION_NET.STAGE3.NUM_BRANCHES = 3
HIGHER_RESOLUTION_NET.STAGE3.NUM_BLOCKS = [4, 4, 4]
HIGHER_RESOLUTION_NET.STAGE3.NUM_CHANNELS = [24, 48, 92]
HIGHER_RESOLUTION_NET.STAGE3.BLOCK = 'BOTTLENECK'
HIGHER_RESOLUTION_NET.STAGE3.FUSE_METHOD = 'SUM'

HIGHER_RESOLUTION_NET.STAGE4 = CN()
HIGHER_RESOLUTION_NET.STAGE4.NUM_MODULES = 1
HIGHER_RESOLUTION_NET.STAGE4.NUM_BRANCHES = 4
HIGHER_RESOLUTION_NET.STAGE4.NUM_BLOCKS = [4, 4, 4, 4]
HIGHER_RESOLUTION_NET.STAGE4.NUM_CHANNELS = [24, 48, 92, 192]
HIGHER_RESOLUTION_NET.STAGE4.BLOCK = 'BOTTLENECK'
HIGHER_RESOLUTION_NET.STAGE4.FUSE_METHOD = 'SUM'

HIGHER_RESOLUTION_NET.DECONV = CN()
HIGHER_RESOLUTION_NET.DECONV.NUM_DCONVS = 2
HIGHER_RESOLUTION_NET.DECONV.NUM_CHANNELS = [32, 32]
HIGHER_RESOLUTION_NET.DECONV.NUM_BASIC_BLOCKS = 4
HIGHER_RESOLUTION_NET.DECONV.KERNEL_SIZE = [2, 2]
HIGHER_RESOLUTION_NET.DECONV.CAT_OUTPUT = [True, True]


MODEL_EXTRAS = {
    'multi_resolution_net_v16': HIGHER_RESOLUTION_NET,
}